[versions]

minecraft = "1.21.1"

# fabric
fabric-loader = "0.19.2"
fabric-kotlin = "1.13.11+kotlin.2.3.21"
fabric-api = "0.116.11+1.21.1"

# neoforge
neoform = "1.21.1-20240808.144430"
neoforge = "21.1.228"
kotlinforforge = "5.11.0"

# plugins
kotlin = "2.3.21"

fabric-loom = "1.16-SNAPSHOT"
neoforged-moddev = "2.0.141"

[libraries]

minecraft = { module = "net.minecraft:minecraft", version.ref = "minecraft" }

fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

kotlinforforge = { module = "thedarkcolour:kotlinforforge-neoforge", version.ref = "kotlinforforge" }

[plugins]

kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

fabric-loom = { id = "net.fabricmc.fabric-loom-remap", version.ref = "fabric-loom" }
neoforged-moddev = { id = "net.neoforged.moddev", version.ref = "neoforged-moddev" }
